# The podfile for any Flutter project.
# To keep this up to date, run 'flutter build ios' locally.

platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting build performance.
ENV['COCOAPODS_DISABLE_STATS'] = '1'

project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
  'Profile' => :profile,
}

def flutter_install_all_ios_pods(ios_application_path = nil)
  native_additions_path = File.join(ios_application_path, 'Flutter', 'ephemeral', 'Packages', 'Flutter')
  # On older versions of Flutter this was 'Flutter/ephemeral/Flutter'
  unless File.exist?(native_additions_path)
    native_additions_path = File.join(ios_application_path, 'Flutter', 'ephemeral', 'Flutter')
  end
  # If we still can't find it, we're likely on a version of Flutter that doesn't use ephemeral packages.
  unless File.exist?(native_additions_path)
    # This path is relative to the Podfile.
    return
  end
  # This is a bit of a hack to get the Flutter framework into the Pods project.
  pod 'Flutter', :path => native_additions_path
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.expand_path('..', __FILE__)
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
